### PR TITLE
Add documentation for Slot component

### PR DESCRIPTION
**Pull request by michalczaplinski**
This is the documentation for the `<Slot/>` component.

Feature Discussion: https://community.frontity.org/t/slot-and-fill/895
PR into `frontity/frontity`: https://github.com/frontity/frontity/pull/475

This is not complete yet. We're missing:

- A general explanation of the Slot and Fill pattern (as already mentioned by @luisherranz https://github.com/frontity/gitbook-docs/pull/75#issuecomment-638158136)
- How to insert the Fills into the state:
  - explain namespaces
  - explain what the `library` property refers to
- More use cases:
  - How to pass props to `Fills` (e.g by setting `state.fills.fillNamespace.fillName.props`)
  - Using multiple Fills with different `priority` in the same slot

etc.

Admittedly, some of the above are more related to how to use the Slot and fill pattern in general.

Let me know if you guys would need more help with this 🙂

### CODE REVIEW

**Comment by michalczaplinski** [comment]
Assigned @mburridge cause you're the supporter this week 🙂

**Comment by luisherranz** [comment]
Hey Michal, I think you've mistakenly added this to `@frontity/components` instead of `frontity`.

Also, as this is not ready yet, I'm going to turn it into a draft 👍

**Comment by juanmaguitar** [comment]
Just to add more context about this

According to [the latest Sprint (Sprint 4) status](https://community.frontity.org/t/sprint-4-review-sprint-5-planning/2135)

> * [Create the Slot component [3pt]](https://github.com/frontity/frontity/pull/475): This one is supposed to be finished. It's just pending the review. Once this is merged, the whole [Slot and Fill](https://community.frontity.org/t/slot-and-fill/895) feature will be finished.

This feature is finished but it's not released yet 

The [code PR](https://github.com/frontity/frontity/pull/475) is merged but the [Feature Discussion](https://community.frontity.org/t/slot-and-fill/895) is still as "Currently in Development" until the feature is released

**Comment by michalczaplinski** [comment]
Hey @mburridge let me know if you need help or more information to finish the documentation here 🙂

**Comment by mburridge** [comment]
@michalczaplinski A couple of questions:

Should the `useFills` hook that is used behind the scenes here also be documented? If so should it be documented here along with the Slot and Fill documentation, or separately elsewhere?

Were data assertions implemented (as described at https://community.frontity.org/t/slot-and-fill/895/3)? Do they need documenting?

**Comment by mburridge** [comment]
@michalczaplinski 

I found the useFills docs so edited my question to remove that. Let me know if more content is needed there. I think you were probably answering just as I edited the question! 😄

I've opened a new PR for this now: https://github.com/frontity/docs/pull/168

**Pull request closed without merging**
